### PR TITLE
Fix package name

### PR DESCRIPTION
**Pull request by camcory**
Allows theme option to show in settings

### CODE REVIEW

**Comment by lbdroid** [comment]
I see what you're getting at, however, we won't be accepting this patch as is, since we are trying to get away from hardcoding the package name in multiple places throughout the code.

And frankly, I can't think of any sensible purpose for those tests to begin with, since they amount to if(I_AM_ME) and if (I_AM_NOT_ME), which is pretty silly.

**Comment by lbdroid** [comment]
You know, rather than closing the pull request, you could update it to take my suggestion into account....

**Comment by camcory** [comment]
Sorry I actually did that should I redo the pull request I removed the package name check.

**Comment by lbdroid** [comment]
The pull request will self-update when you make changes to the branch you are making the request from.

**Pull request closed without merging**
